#!/bin/bash
# Generated by vim-plug
# Sun 08 Feb 2015 08:17:53 PM GMT

vim +PlugUpdate +qa

PLUG_HOME=/home/pascal/.nvim/plugged

cd $PLUG_HOME/ctrlp.vim/ && git reset --hard b5d3fe6
cd $PLUG_HOME/delimitMate/ && git reset --hard 66834e7
cd $PLUG_HOME/elm.vim/ && git reset --hard 69fa9a4
cd $PLUG_HOME/ghcmod-vim/ && git reset --hard d5c6c7f
cd $PLUG_HOME/haskellmode-vim/ && git reset --hard 8db4731
cd $PLUG_HOME/lightline.vim/ && git reset --hard 72a413e
cd $PLUG_HOME/neco-ghc/ && git reset --hard fffdf57
cd $PLUG_HOME/neocomplcache.vim/ && git reset --hard 2374429
cd $PLUG_HOME/powerline/ && git reset --hard 39dda39
cd $PLUG_HOME/purescript-vim/ && git reset --hard 7eba599
cd $PLUG_HOME/syntastic/ && git reset --hard 64cce20
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-commentary/ && git reset --hard 401dbd8
cd $PLUG_HOME/vim-fish/ && git reset --hard 705db65
cd $PLUG_HOME/vim-flow/ && git reset --hard df271c8
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 0374322
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 39f0119
cd $PLUG_HOME/vim-gradle/ && git reset --hard e77153d
cd $PLUG_HOME/vim-hdevtools/ && git reset --hard cdf2ce1
cd $PLUG_HOME/vim-hsimport/ && git reset --hard 6249747
cd $PLUG_HOME/vim-markdown/ && git reset --hard 409c37b
cd $PLUG_HOME/vim-paren-crosshairs/ && git reset --hard 38eb677
cd $PLUG_HOME/vim-repeat/ && git reset --hard 2a3c5f8
cd $PLUG_HOME/vim-sensible/ && git reset --hard 64aa12b
cd $PLUG_HOME/vim-sleuth/ && git reset --hard 6b0c9d6
cd $PLUG_HOME/vim-smartinput/ && git reset --hard 78ab4b3
cd $PLUG_HOME/vim-surround/ && git reset --hard fa433e0
cd $PLUG_HOME/vim-textobj-indent/ && git reset --hard deb7686
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard 9aa5fd0
cd $PLUG_HOME/vim-toml/ && git reset --hard bb70afc
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 3548479
cd $PLUG_HOME/vimproc/ && git reset --hard 59a09d1
cd $PLUG_HOME/vimux/ && git reset --hard 50254fa

