#!/bin/sh
# Generated by vim-plug
# Fri May  1 14:35:13 2015

vim +PlugUpdate +qa

PLUG_HOME=/Users/phartig/.nvim/plugged

cd $PLUG_HOME/delimitMate/ && git reset --hard c78a6e6
cd $PLUG_HOME/elm.vim/ && git reset --hard 9168427
cd $PLUG_HOME/ghcmod-vim/ && git reset --hard 7e5f610
cd $PLUG_HOME/haskell-vim/ && git reset --hard 02a6965
cd $PLUG_HOME/lightline.vim/ && git reset --hard b967eef
cd $PLUG_HOME/neco-ghc/ && git reset --hard a45f4f9
cd $PLUG_HOME/neocomplcache.vim/ && git reset --hard 7781817
cd $PLUG_HOME/neomake/ && git reset --hard 6d320d3
cd $PLUG_HOME/powerline/ && git reset --hard 8164f42
cd $PLUG_HOME/purescript-vim/ && git reset --hard ba14567
cd $PLUG_HOME/rust.vim/ && git reset --hard 0becec1
cd $PLUG_HOME/syntastic/ && git reset --hard 9af644d
cd $PLUG_HOME/tabular/ && git reset --hard 60f2564
cd $PLUG_HOME/undotree/ && git reset --hard fa018f3
cd $PLUG_HOME/unite.vim/ && git reset --hard 32fd680
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 32fe889
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-commentary/ && git reset --hard 9c68513
cd $PLUG_HOME/vim-fish/ && git reset --hard 705db65
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 4cc201c
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 937930e
cd $PLUG_HOME/vim-gradle/ && git reset --hard 8736039
cd $PLUG_HOME/vim-haskellConcealPlus/ && git reset --hard 9c12f6d
cd $PLUG_HOME/vim-hdevtools/ && git reset --hard cdf2ce1
cd $PLUG_HOME/vim-hsimport/ && git reset --hard 6249747
cd $PLUG_HOME/vim-markdown/ && git reset --hard 409c37b
cd $PLUG_HOME/vim-paren-crosshairs/ && git reset --hard 6cf9e7b
cd $PLUG_HOME/vim-repeat/ && git reset --hard c4f9f15
cd $PLUG_HOME/vim-sensible/ && git reset --hard d0beb8a
cd $PLUG_HOME/vim-sleuth/ && git reset --hard 1db371f
cd $PLUG_HOME/vim-smartinput/ && git reset --hard 78ab4b3
cd $PLUG_HOME/vim-surround/ && git reset --hard 772ab95
cd $PLUG_HOME/vim-textobj-indent/ && git reset --hard deb7686
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard 6b7255e
cd $PLUG_HOME/vim-toml/ && git reset --hard 190a55c
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 3548479
cd $PLUG_HOME/vimproc/ && git reset --hard ec82640
cd $PLUG_HOME/vimux/ && git reset --hard a1db730
