#!/bin/sh
# Generated by vim-plug
# Mon Apr 13 10:59:46 2015

vim +PlugUpdate +qa

PLUG_HOME=/Users/phartig/.nvim/plugged

cd $PLUG_HOME/delimitMate/ && git reset --hard 470c053
cd $PLUG_HOME/elm.vim/ && git reset --hard 928ddc0
cd $PLUG_HOME/ghcmod-vim/ && git reset --hard d5c6c7f
cd $PLUG_HOME/haskell-vim/ && git reset --hard 02a6965
cd $PLUG_HOME/lightline.vim/ && git reset --hard 38751ed
cd $PLUG_HOME/neco-ghc/ && git reset --hard 43d8ef4
cd $PLUG_HOME/neocomplcache.vim/ && git reset --hard d83bcbd
cd $PLUG_HOME/neomake/ && git reset --hard 5802c65
cd $PLUG_HOME/powerline/ && git reset --hard 34f53ac
cd $PLUG_HOME/purescript-vim/ && git reset --hard ba14567
cd $PLUG_HOME/rust.vim/ && git reset --hard 78301c5
cd $PLUG_HOME/syntastic/ && git reset --hard 1c6cae0
cd $PLUG_HOME/tabular/ && git reset --hard 60f2564
cd $PLUG_HOME/undotree/ && git reset --hard 42000e2
cd $PLUG_HOME/unite.vim/ && git reset --hard 8460f65
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 827e4a3
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-commentary/ && git reset --hard 9c68513
cd $PLUG_HOME/vim-fish/ && git reset --hard 705db65
cd $PLUG_HOME/vim-fugitive/ && git reset --hard eb8eb18
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 061258e
cd $PLUG_HOME/vim-gradle/ && git reset --hard e77153d
cd $PLUG_HOME/vim-haskellConcealPlus/ && git reset --hard 75f2ca1
cd $PLUG_HOME/vim-hdevtools/ && git reset --hard cdf2ce1
cd $PLUG_HOME/vim-hsimport/ && git reset --hard 6249747
cd $PLUG_HOME/vim-markdown/ && git reset --hard 409c37b
cd $PLUG_HOME/vim-paren-crosshairs/ && git reset --hard 6cf8ae0
cd $PLUG_HOME/vim-repeat/ && git reset --hard b06684a
cd $PLUG_HOME/vim-sensible/ && git reset --hard b30dcf3
cd $PLUG_HOME/vim-sleuth/ && git reset --hard b6b4c3b
cd $PLUG_HOME/vim-smartinput/ && git reset --hard 78ab4b3
cd $PLUG_HOME/vim-surround/ && git reset --hard fd75eb2
cd $PLUG_HOME/vim-textobj-indent/ && git reset --hard deb7686
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard 9aa5fd0
cd $PLUG_HOME/vim-toml/ && git reset --hard bb70afc
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 3548479
cd $PLUG_HOME/vimproc/ && git reset --hard 04b45cd
cd $PLUG_HOME/vimux/ && git reset --hard a991ce8

